version: '3'
services:
  gin-backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Map the PostgreSQL port to avoid conflicting with the default port
    volumes:
      - postgresql_data:/var/lib/postgresql/data # persist database changes after container stop

volumes:
  postgresql_data:
