# Use the official PostgreSQL 12 image as the base image
FROM postgres:12

# Environment variables for PostgreSQL database, user, and password
ENV POSTGRES_DB ct
ENV POSTGRES_USER ct
ENV POSTGRES_PASSWORD password

# Expose the default PostgreSQL port (5432)
EXPOSE 5432
