#!/bin/bash

backend_root="backend/"
# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

### Execute backend commands ###

cd ${backend_root}

# Check if poetry is available
if ! command_exists "poetry"; then
    echo "Error: poetry must be installed for this hook. Install it following the README in backend/."
    exit 1
fi
 
# Run black in check mode
if ! poetry run black --check .; then
    echo "Error: Unformatted code detected. Running black formatter."
    poetry run black .
    echo "Stage the newly formatted files with 'git add' ('git add .' to stage all files )."
    exit 1
fi

cd .. # return back to root dir

### Execute frontend commands ###


exit 0

