"""Add term-year to schedule model

Revision ID: 18cafb92980f
Revises: f5525cc76f06
Create Date: 2023-10-30 23:23:13.424962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18cafb92980f"
down_revision: Union[str, None] = "f5525cc76f06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("term", sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column("year", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.drop_column("year")
        batch_op.drop_column("term")

    # ### end Alembic commands ###
