"""Initial Prod Migration Script

Revision ID: f5525cc76f06
Revises: 
Create Date: 2023-10-24 09:49:54.541307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5525cc76f06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('docId', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('filetype', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('lastModified', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.UserId'], ),
    sa.PrimaryKeyConstraint('docId')
    )
    op.create_table('Resume',
    sa.Column('resumeId', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('filetype', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('lastModified', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.UserId'], ),
    sa.PrimaryKeyConstraint('resumeId')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.UserId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_section.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_schedule')
    op.drop_table('schedule')
    op.drop_table('Resume')
    op.drop_table('Document')
    # ### end Alembic commands ###
