name: Daily Project Metrics Generation

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual trigger from the GitHub UI

jobs:
  generate_and_commit_metrics:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout current code
        uses: actions/checkout@v4
      - name: Checkout INSO GH Metrics code
        uses: actions/checkout@v4
        with:
          repository: Poggecci/INSO-GH-API-QUERY
          path: inso-gh-query-metrics
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests
        shell: bash
      - name: Run metrics generator
        run: python inso-gh-query-metrics/exportMetricsForCourseMilestone.py ${{ github.workspace}}/gh_metrics_config.json
        shell: bash
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
      - name: Move Generated Metrics to src repo
        run: mv **/*.csv ./
      - name: Auto Commit Results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated metrics update
          branch: ${{ github.ref }}
          file_pattern: . # Adjust if you want to specify paths to commit
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          commit_author: GitHub Action <action@github.com>
